#!/usr/bin/env bash
# =============================================================================
# setup-minicom-beagleboard.sh — Create a minicom profile for BeagleBoard UART
# =============================================================================
set -euo pipefail

PROFILE="${MINICOM_PROFILE:-beagleboard}"
DEVICE="${MINICOM_DEVICE:-/dev/ttyUSB0}"
BAUDRATE="${MINICOM_BAUD:-115200}"
STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}"
LOG_DIR="${MINICOM_LOG_DIR:-$STATE_DIR/minicom}"
LOG_FILE="${MINICOM_LOG_FILE:-$LOG_DIR/${PROFILE}.log}"
CONFIG_FILE="$HOME/.minirc.${PROFILE}"
TMP_FILE="$(mktemp)"

cleanup() {
    rm -f "$TMP_FILE"
}
trap cleanup EXIT

if ! command -v minicom >/dev/null 2>&1; then
    echo "error: minicom is not installed" >&2
    echo "hint: install it first (e.g. sudo apt install minicom)" >&2
    exit 1
fi

mkdir -p "$LOG_DIR"

cat >"$TMP_FILE" <<EOF
# Generated by setup-minicom-beagleboard.sh
pu port             $DEVICE
pu baudrate         $BAUDRATE
pu bits             8
pu parity           N
pu stopbits         1
pu rtscts           No
pu xonxoff          No
pu localecho        No
pu linewrap         Yes
pu addcarreturn     No
pu logfile          YES
pu logfname         $LOG_FILE
EOF

if [ -e "$CONFIG_FILE" ] && ! cmp -s "$TMP_FILE" "$CONFIG_FILE"; then
    backup="${CONFIG_FILE}.bak.$(date +%Y%m%d%H%M%S)"
    cp "$CONFIG_FILE" "$backup"
    echo "backup: $CONFIG_FILE -> $backup"
fi

install -m 600 "$TMP_FILE" "$CONFIG_FILE"

echo "created: $CONFIG_FILE"
echo "device : $DEVICE"
echo "baud   : $BAUDRATE"
echo "log    : $LOG_FILE"
echo ""
echo "connect with:"
echo "  minicom $PROFILE"
